version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/apakai?schema=public
    volumes:
      - ./public:/app/public
      - /app/node_modules
      - /app/.next
      - ./app:/app/app
      - ./prisma:/app/prisma
    depends_on:
      - db
    restart: always

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apakai
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./public:/app/public:rw
    depends_on:
      - web
    restart: always
    command: /bin/sh -c 'chmod -R 777 /app/public; find /app/public -type f -exec chmod 644 {} +; nginx -g "daemon off;"'

volumes:
  postgres_data: 