version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:12345@db:5432/postgres?schema=public
      - JWT_SECRET=ApakaiStore16032025
      - NEXTAUTH_URL=http://62.113.41.23
      - NEXTAUTH_SECRET=ApakaiStore16032025
    depends_on:
      - db
    networks:
      - app_network

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge 